apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: dev
spec:
  selector:
    app: sampleapp
  ports:
    - port: 8080 
      targetPort: 8080 # Give port of your java application
  type: LoadBalancer
