apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - port: 80 
      targetPort: 80 # Give port of your java application
  type: LoadBalancer
